routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/','PersonController@index')->middleware('auth');
route::get('profile','PersonController@show_detail')->name('profile');
Route::get('income/{id?}','IncomeController@show');
Route::get('expend/{id?}','ExpendController@show');
Route::get('summary/{id?}','SummaryController@show');
Route::get('account','AccountController@index');

route::get('pdf/{val?}','ExportController@pdf');
route::get('print','ExportController@createPDF');

Route::get('/phpinfo',function(){
    return phpinfo();
});

Route::prefix('manage')->group(function(){
    #Route::get('/','ManageController@index')->name('manage.index');   
    Route::resource('menu','MenuController');   
    Route::get('menu/edit/{id}','MenuController@edit'); 
    Route::post('/menu_change_status','MenuController@change_status')->name('menu_change_status'); 

    Route::resource('group','RolesController');  
    Route::resource('permis','PermisController');  
    #Route::get('permis/{id?}','PermisController');  
    route::get('changepermis/{id?}','PermisController@changepermis');
});


Route::prefix('main')->group(function(){

    Route::resource('person','PersonController'); 
    Route::resource('jd','CategoryController');
    /*
    Route::resource('income','IncomeController'); 
    Route::get('income/edit/{id}','IncomeController@edit'); 
    Route::post('/income_change_status','IncomeController@change_status')->name('income_change_status');

    Route::resource('expend','ExpendController');
    Route::get('expend/edit/{id}','ExpendController@edit'); 
    Route::post('/expend_change_status','ExpendController@change_status')->name('expend_change_status');
    */
    
});

Route::prefix('fin')->group(function(){
    
    Route::resource('salary','SalaryController'); 
    Route::get('salary/edit/{id}','SalaryController@edit'); 
    Route::post('/salary_change_status','SalaryController@change_status')->name('salary_change_status');
    Route::post('/salary/search','SalaryController@search')->name('search');

    Route::resource('assign_expend','AssignExpendController'); 
    Route::post('assign_person/{id}','AssignExpendController@create_person'); 
    Route::get('assign_person/{id}','AssignExpendController@create_person');  
    Route::get('match_per_expend','AssignExpendController@match_person'); 
    Route::get('match_per_expend_step2/{id}','AssignExpendController@match_person_step2');
    Route::post('match_per_expend_step2','AssignExpendController@create_person_expend');  
    Route::get('salary_rate','SalaryController@salary_rate'); 
    Route::post('/rate/search','SalaryController@rate_search')->name('search_rate');


    
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/ExpendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\slip_item;
use App\sys_menu;
use App\sys_month;
use App\sys_year;
use App\mas_campus;
use App\vw_slip_expend;
use Auth;
use App\vw_his_person;

class ExpendController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $camp_id = session('camp_id');
        #return $camp_id;
       /*
        $data['menu'] = sys_menu::where('menu_in','main')
                        ->where('record_status','N')   
                        ->where('system_delete','none')        
                        ->orderby('menu_order')
                        ->get();
        $data['sub_menu'] = sys_menu::where('menu_in','<>','main')
                        ->where('record_status','N')  
                        ->where('system_delete','none')         
                        ->orderby('menu_order')
                        ->get(); 
       */                
        $data['expend'] = slip_item::where('RECORD_STATUS','N')
                        ->where('item_type','expend')       
                        #->whereIn('item_campus',['1'])                 
                        ->where('item_campus','LIKE','%'.$camp_id.'%')
                        ->orderby('id')
                        ->paginate(20);
                        #->get();                                                  
        #return $data;
        return view('expend.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        /*
        $data['menu'] = sys_menu::where('menu_in','main')
                        ->where('record_status','N')       
                        ->where('system_delete','none')    
                        ->orderby('menu_order')
                        ->get();
        $data['sub_menu'] = sys_menu::where('menu_in','<>','main')
                        ->where('record_status','N')       
                        ->where('system_delete','none')    
                        ->orderby('menu_order')
                        ->get();  
        */          
        $data['campus']  = mas_campus::where('record_status','N') 
                        ->orderby('campus_id')
                        ->get();

        
        return view('expend.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = slip_item::max('id');
        $id = $id+1;

        $arrCampus = json_encode($request->item_campus);
        #return $arrCampus;

        $expend = new slip_item();
        $expend->id                 = $id;
        $expend->item_name_th        = $request->item_name_th;
        $expend->item_name_en        = $request->item_name_en;
        $expend->item_campus         = $arrCampus;
        $expend->item_price          = $request->item_price;
        $expend->item_rate           = $request->item_rate;
        $expend->RECORD_STATUS      = $request->RECORD_STATUS;
        $expend->item_type          = 'expend';
        $expend->system_delete      = 'none';

        #return $expend;
        $expend->save();
        return redirect()->action('ExpendController@index')->with('alert','บันทึกข้อมูลเรียบร้อยแล้ว'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id=null)
    {
        $camp_id = session('camp_id');
        #return session('camp_id');
        if (empty($id)) {
            #$select_M = date('n');  
            $M = vw_slip_expend::select('slip_month')
                        ->where('person_id', Auth::user()->vw_his_person->person_id)
                        ->orderby('slip_month','DESC')
                        ->first();   
            $select_M = $M->slip_month;           
        }else{
            $select_M = $id;                    
        }    
        #return $select_M;
        $select_Y = date('Y');
        $data['select_M'] = $select_M;
        $data['select_Y'] = $select_Y;  
             
        $data['sys_month'] = sys_month::where('record_status','N')->orderby('id')->get();
        $data['sys_year'] = sys_year::where('record_status','N')->orderby('id','desc')->get();
        $data['slip_item'] = slip_item::where('RECORD_STATUS','N')->where('item_campus','LIKE','%'.$camp_id.'%')->get();
        #return $data['slip_item'];
        $data['expend'] = vw_slip_expend::where('person_id', Auth::user()->vw_his_person->person_id)
                            ->where('slip_month',$select_M)
                            ->get();
        $data['his_person'] = vw_his_person::where('person_id',Auth::user()->vw_his_person->person_id)->first();

        return view('expend.show',$data);     
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        /*
         $data['menu'] = sys_menu::where('menu_in','main')
                        ->where('record_status','N')       
                        ->where('system_delete','none')    
                        ->orderby('menu_order')
                        ->get();
        $data['sub_menu'] = sys_menu::where('menu_in','<>','main')
                        ->where('record_status','N')       
                        ->where('system_delete','none')    
                        ->orderby('menu_order')
                        ->get();
         */            
        $data['campus']  = mas_campus::where('record_status','N') 
                        ->orderby('campus_id')
                        ->get();
        $data['expend'] = slip_item::where('id',$id)
                        ->get();

        return view('expend.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $arrCampus = json_encode($request->item_campus);

        $expend = slip_item::find($id);    
        $expend->item_name_th        = $request->item_name_th;
        $expend->item_name_en        = $request->item_name_en;
        $expend->item_campus         = $arrCampus;
        $expend->item_price          = $request->item_price;
        $expend->item_rate           = $request->item_rate;
        $expend->RECORD_STATUS      = $request->RECORD_STATUS;

        #return $expend;
        $expend->save();        
        return redirect()->action('ExpendController@index')->with('alert','บันทึกข้อมูลเรียบร้อยแล้ว');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $update = slip_item::find($id);
        $update->system_delete = "delete";        
        $update->save();  
        return back()->with('alert-class','success')->with('alert','ลบข้อมูลแล้ว');
        #return "ddddd";
    }

    public function change_status(Request $request)
    {
        // return "change_status : ".$id;
        $update = slip_item::find($request->id);
        $update->RECORD_STATUS = $request->RECORD_STATUS;
        #$update->updated_by = Auth::user()->username;
        $update->save();
        if($request->RECORD_STATUS == 'N'){
            return back()->with('alert-class','success')->with('alert','ออนไลน์เนื้อหาแล้ว');
        }else{
            return back()->with('alert-class','danger')->with('alert','ออฟไลน์เนื้อหาแล้ว');
        }
    }
}

resources/views/expend/assign.blade.php
@extends('layout.master')
@section('content')

@if( session('alert'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('alert')}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

<div class="container">

    <div class="card">
        <div class="card-header h3">
            กำหนดรายจ่ายของบุคลากร ตามประเภทรายจ่าย ( Assign Expend Management )
        </div>
        <div class="card-body">        

        <div class="row"> {{-- search --}}
            <div class="input-group mb-3 mt-2">
                <input type="text" class="form-control" placeholder="search content" >
                <div class="input-group-append">
                  <button class="btn btn-info" type="button">SEARCH</button>
                </div>
            </div>                           
        </div> {{-- search --}}
        
        {{-- 
        <div class="row d-flex flex-row-reverse"> {{-- add list }}
            <a href="{{ route('expend.create') }}">
                <button type="button" class="btn btn-success">ADD LIST</button>
            </a>                
        </div>{{-- add list }}    
        --}}

            <table class="table table-hover">
                <thead>
                    <tr class="card_bg_topic">
                        <th>#</th>
                        <th></th>
                        <th>name</th>
                        <th>status</th>
                        <th class="text-center">กำหนดรายชื่อ</th>                        
                    </tr>
                </thead>
                
                <tbody>
                @foreach ($expend as $key=>$arrExpend)               
                @if ($arrExpend->RECORD_STATUS == "D")
                    <tr class="table-danger">  
                @else
                    <tr>
                @endif                 
                        <td>{{ $key+1 }}</td>
                        <td>-</td>
                        <td>{{ $arrExpend->item_name_th }}</td>
                        <td>
                            <div class="custom-control custom-switch">                                                        
                                @if ($arrExpend->RECORD_STATUS == 'D')
                                    <input type="checkbox" class="custom-control-input" disabled >
                                @else                                    
                                    <input type="checkbox" class="custom-control-input" disabled checked="">                                
                                @endif
                                    <label class="custom-control-label" for="{{$arrExpend->id}}">ออนไลน์</label>                                
                            </div>
                        </td>
                        <td class="text-center">                            
                            <a href="{{ url('fin/assign_person/'.$arrExpend->id) }}" class="btn btn-sm btn-primary"><i class="fas fa-plus"></i></a>
                        </td>                        
                    </tr>                    
                @endforeach
                </tbody>                                
            </table>        
        </div>
    </div>

</div>

@endsection

resources/views/expend/create.blade.php
@extends('layout.master')
@section('content')

<div class="container">

    <div class="card">
        <div class="card-header h3">
            เพิ่มรายการ : CREATE
        </div>

        <div class="card-body">
        <form action="{{ route('expend.store') }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}       

        <div class="row"> {{-- row form --}}
            <div class="mt-2 col-12">
                                            

                {{-- name TH --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ชื่อเรียก ภาษาไทย (Name thai)</span>
                    </div>
                    <input type="text" class="form-control" name="item_name_th" value="" aria-describedby="basic-addon1">
                </div>            
    
                {{-- name EN --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ชื่อเรียก ภาษาอังกฤษ (Name eng)</span>
                    </div>
                    <input type="text" class="form-control" name="item_name_en" value="" aria-describedby="basic-addon1">
                </div>

                {{-- campus --}}                      
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ศูนย์พื้นที่ (Chart)</span>
                    </div>
                    <div class="ml-2">                                                                               
                        @foreach ($campus as $arrCampus)
                            <div class="form-check form-check-inline ml-2"> 
                                <input class="form-check-input" name="item_campus[]" type="checkbox" id="inlineCheckbox1" value="{{ $arrCampus->campus_id }}">
                                <label class="form-check-label" for="inlineCheckbox1">{{ $arrCampus->campus_name_th }}</label>
                            </div>
                        @endforeach                        
                    </div>
                </div>

                {{-- price --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">จำนวนเงิน (บาท)</span>
                    </div>
                    <input type="text" class="form-control" name="item_price" value="" aria-describedby="basic-addon1">
                </div>

                {{-- rate --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ร้อยละ (%)</span>
                    </div>
                    <input type="text" class="form-control" name="item_rate" value="" aria-describedby="basic-addon1">
                </div>
                
                {{-- status --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">สถานะ (Status)</span>
                    </div>
                    <div class="form-check ml-2">
                        <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="N" checked>
                        <label class="form-check-label" for="exampleRadios1">Online</label>
                    </div> 
                    <div class="form-check ml-2">
                        <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="D" >
                        <label class="form-check-label" for="exampleRadios1">Offline</label>
                    </div>                        
                </div>
            </div> {{-- <div class="mt-2"> --}}
        </div>

        <div class="row">
            <button type="submit" class="btn btn-info m-3">SAVE</button>
            <a href="" class="m-3"><button type="button" class="btn btn-secondary">RESET</button></a> 
        </div> {{-- row buttom --}}

        </form> {{-- row form --}}
        </div>{{-- <div class="card-body"> --}}
    </div>

</div>

@endsection

resources/views/expend/frm_ass_person.blade.php
@extends('layout.master')
@section('content')

<div class="container">

    <div class="card">
        <div class="card-header h3">
            @foreach ($expend as $arrExpend)
                กำหนดรายจ่ายให้บุคลากร -> <b>{{ $arrExpend->item_name_th }}</b>
                @php
                  $exp_id =  $arrExpend->id;
                @endphp
            @endforeach
            ประจำเดือน xxxx ปี xxxx            
        </div>

        <div class="card-body">        
            {{-- 
            <div class="row"> {{-- search - -}}                
                <form action="{{ url('fin/assign_person/'.$exp_id) }}" method="post"> {{-- form search - -}}
                {{ csrf_field() }}

                    {{-- row -- }}            
                    <div class="row">                        
                        <div class="col-12">
                            {{-- 1 - -}}            
                            {{-- faculty - -}}                              
                            <div class="input-group mb-1">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">ศูนย์พื้นที่ : </span>
                                </div>
                                <select class="form-control" name="campus" >
                                    <option value="">:: เลือก ::</option>         
                                    @foreach ($campus as $arrCampus)
                                        <option value="{{ $arrCampus->campus_id }}" {{ $arrCampus->campus_id==$camp_id ? 'selected':'' }} >{{ $arrCampus->campus_name_th }}</option>
                                    @endforeach                                 
                                </select>
                            </div>    
                        </div>                
                    </div>                    
        
                    <div class="input-group mt-2 mb-2">
                        <div class="input-group-append">
                          <button class="btn btn-info" type="submit"><i class="fas fa-search"></i> SEARCH</button>
                        </div>
                    </div>           
                                      
                </form>{{-- form search - -}}
            </div> {{-- search -}}
            --}}
        
            <div class="row"> {{-- search --}}                
                <form action="{{ route('search') }}" method="post"> {{-- form search --}}
                {{ csrf_field() }}
                
                    {{-- row --}}            
                    <div class="row">
                        <div class="col-6">
                            {{-- 1 --}}            
                            {{-- faculty --}}            
                            <div class="input-group mb-1">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">หน่วยงาน : </span>
                                </div>
                                <select class="form-control" name="faculty" >
                                    <option value="">:: เลือก ::</option>         
                                    @foreach ($faculty as $arrFaculty)
                                        <option value="{{ $arrFaculty->faculty_id }}"  >{{ $arrFaculty->faculty_name_th }}</option>
                                    @endforeach                                 
                                </select>
                            </div>
                        </div>
                        <div class="col-6">
                            {{-- 2 --}}            
                            {{-- faculty --}}            
                            <div class="input-group mb-1">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">ศูนย์พื้นที่ : </span>
                                </div>
                                <select class="form-control" name="campus" >
                                    <option value="">:: เลือก ::</option>         
                                    @foreach ($campus as $arrCampus)
                                        <option value="{{ $arrCampus->campus_id }}"  >{{ $arrCampus->campus_name_th }}</option>
                                    @endforeach                                 
                                </select>
                            </div>
                        </div>                
                    </div>
    
                    {{-- row --}}            
                    <div class="row">
                        <div class="col-6">
                            {{-- 1 --}}            
                            {{-- workline --}}            
                            <div class="input-group mb-1">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">สายงาน : </span>
                                </div>
                                <select class="form-control" name="workline" >
                                    <option value="">:: เลือก ::</option>         
                                    @foreach ($workline as $arrWorkline)
                                        <option value="{{ $arrWorkline->workline_id }}  ">{{ $arrWorkline->workline_name_th }}</option>
                                    @endforeach                                 
                                </select>
                            </div>
                        </div>
                        <div class="col-6">
                            {{-- 2 --}}            
                            
                        </div>                
                    </div>
        
                    {{-- name --}}            
                    <div class="input-group mb-1">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">ชื่อ - สกุล : </span>
                        </div>
                        <input type="text" class="form-control" name="name_search" value="" disabled aria-describedby="basic-addon1">
                    </div>
        
                    <div class="input-group mt-2 mb-2">
                        <div class="input-group-append">
                          <button class="btn btn-info" type="submit">SEARCH</button>
                        </div>
                    </div>           
                                      
                </form>{{-- form search --}}
            </div> {{-- search --}}


        <form action="{{ route('assign_expend.store') }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}       
                    

            <input type="hidden" name="exp_id" value="{{ $exp_id }}">
            <input type="hidden" name="campus_id" value="{{ $camp_id }}">
            <input type="hidden" name="exp_month" value="{{ $exp_month }}">
            <input type="hidden" name="exp_year" value="{{ $exp_year }}">

            <div class="row"> {{-- row form --}}
                <div class="mt-2 col-12">
                    
                    <table class="table table-hover">
                        <thead>
                            <tr class="card_bg_topic">
                                <th>#</th>                            
                                <th>name</th>
                                <th class="text-left">
                                    กำหนดรายชื่อ
                                    {{-- 
                                    <div class="form-check">
                                        <input type="checkbox" class="select-all checkbox" name="select-all" /> เลือกทั้งหมด                           
                                    </div> 
                                    --}}                               
                                </th>                        
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($search as $item)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $item->vw_his_person->getfullname() }}</td>
                                <td class="text-left">
                                    <div class="row">
                                        <div class="form-check">                                                
                                            <input type="checkbox" id="myCheck" value="{{ $loop->index }}" name="chk_person[]" onclick="myFunction(this.value)">
                                            <input type="hidden" name="data[{{ $loop->index }}][person_id]" value="{{ $item->person_id }}" >
                                        </div>
                                        <div>
                                            <p id="{{ $loop->index }}" style="display:none">ระบุจำนวนเงิน : <input type="number" name="data[{{ $loop->index }}][exp_price]" id="exp_price" class="form-control ml-2"></p>
                                        </div>                                            
                                    </div>
                                </td>
                            </tr>      
                            @endforeach                                                  
                        </tbody>
                    </table>

                </div> {{-- <div class="mt-2"> --}}
            </div>
           
            <div class="row">{{-- row buttom --}}
                <button type="submit" class="btn btn-info m-3">NEXT</button>                
                <button type="reset" class="btn btn-secondary m-3">RESET</button>
            </div> {{-- row buttom --}}
           

        </form> {{-- row form --}}
        

            
        </div>{{-- <div class="card-body"> --}}
    </div>

</div>

@endsection

@section('script')

<script>
    function myFunction($id) {
    //alert($id);
      var checkBox = document.getElementById("myCheck");
      //var text = document.getElementById("text");
      /*
      if (checkBox.checked == true){
        text.style.display = "block";
      } else {
         text.style.display = "none";
      }
      */
      if (checkBox.checked == true){
            //alert($id);
            var text = document.getElementById($id);
            text.style.display = "block";        
      }else {
            //alert("-");
            text.style.display = "none";
      }
    }
    </script>
@endsection