routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/','PersonController@index')->middleware('auth');
route::get('profile','PersonController@show_detail')->name('profile');
Route::get('income/{id?}','IncomeController@show');
Route::get('expend/{id?}','ExpendController@show');
Route::get('summary/{id?}','SummaryController@show');
Route::get('account','AccountController@index');

route::get('pdf/{val?}','ExportController@pdf');
route::get('print','ExportController@createPDF');

Route::get('/phpinfo',function(){
    return phpinfo();
});

Route::prefix('manage')->group(function(){
    #Route::get('/','ManageController@index')->name('manage.index');   
    Route::resource('menu','MenuController');   
    Route::get('menu/edit/{id}','MenuController@edit'); 
    Route::post('/menu_change_status','MenuController@change_status')->name('menu_change_status'); 

    Route::resource('group','RolesController');  
    Route::resource('permis','PermisController');  
    #Route::get('permis/{id?}','PermisController');  
    route::get('changepermis/{id?}','PermisController@changepermis');
});


Route::prefix('main')->group(function(){

    Route::resource('person','PersonController'); 
    Route::resource('jd','CategoryController');
    /*
    Route::resource('income','IncomeController'); 
    Route::get('income/edit/{id}','IncomeController@edit'); 
    Route::post('/income_change_status','IncomeController@change_status')->name('income_change_status');

    Route::resource('expend','ExpendController');
    Route::get('expend/edit/{id}','ExpendController@edit'); 
    Route::post('/expend_change_status','ExpendController@change_status')->name('expend_change_status');
    */
    
});

Route::prefix('fin')->group(function(){
    
    Route::resource('salary','SalaryController'); 
    Route::get('salary/edit/{id}','SalaryController@edit'); 
    Route::post('/salary_change_status','SalaryController@change_status')->name('salary_change_status');
    Route::post('/salary/search','SalaryController@search')->name('search');

    Route::resource('assign_expend','AssignExpendController'); 
    Route::post('assign_person/{id}','AssignExpendController@create_person'); 
    Route::get('assign_person/{id}','AssignExpendController@create_person');  
    Route::get('match_per_expend','AssignExpendController@match_person'); 
    Route::get('match_per_expend_step2/{id}','AssignExpendController@match_person_step2');
    Route::post('match_per_expend_step2','AssignExpendController@create_person_expend');  
    Route::get('salary_rate','SalaryController@salary_rate'); 
    Route::post('/rate/search','SalaryController@rate_search')->name('search_rate');


    
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/SalaryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\vw_his_person;
use App\sys_menu;
use App\mas_faculty;
use App\mas_campus;
use App\mas_workline;
use App\vw_sly_rate;


class SalaryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {              
        $data['faculty'] = mas_faculty::where('record_status','N')->orderby('faculty_id')->get();
        $data['campus'] = mas_campus::where('record_status','N')->orderby('campus_id')->get();
        $data['workline'] = mas_workline::where('record_status','N')->orderby('workline_id')->get();                                                

        return view('salary.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function search(Request $request)
    {      
        $data['faculty'] = mas_faculty::where('record_status','N')->orderby('faculty_id')->get();
        $data['campus'] = mas_campus::where('record_status','N')->orderby('campus_id')->get();
        $data['workline'] = mas_workline::where('record_status','N')->orderby('workline_id')->get(); 
        #if(empty($request)){
        #    $data['search'] = vw_his_person::where('statuslist','9');
        #}else{                                     
            $data['search'] = vw_his_person::where('statuslist','9');

                if (isset($request->faculty)) {
                    $data['search'] = $data['search']->where('faculty_id',$request->faculty);
                }

                if (isset($request->campus)) {
                    $data['search'] = $data['search']->where('campus_id',$request->campus);
                }

                if (isset($request->workline)) {
                    $data['search'] = $data['search']->where('workline_id',$request->workline);
                }

                if (isset($request->name_search)) {
                    $data['search'] = $data['search']->where('fname_th',$request->name_search)->orwhere('lname_th',$request->name_search);
                }
            
            $data['search'] = $data['search']->get();
                            /*->paginate(20);*/
                                                                                            
            $data['facu_id'] = $request->faculty;
            $data['camp_id'] = $request->campus;
            $data['work_id'] = $request->workline;
        #}
        
        return view('salary.index',$data);     
    }

    public function salary_rate()
    {

        $data['chk_faculty'] = "";   
        $data['chk_campus']  = session('camp_id');
        $data['chk_workline']  = "";

        $data['faculty'] = mas_faculty::where('record_status','N')->orderby('faculty_id')->get();
        $data['campus'] = mas_campus::where('record_status','N')->orderby('campus_id')->get();
        $data['workline'] = mas_workline::where('record_status','N')->orderby('workline_id')->get(); 
        #$data['sly_rate'] = vw_sly_rate::where('rate_status_id','2')->count();        
        $data['sly_rate'] = vw_his_person::where('statuslist','9')->count();        
        $data['search'] = vw_his_person::where('statuslist','9');
        $data['count_search'] = 0;
        return view('salary.sly',$data);
    }

    public function rate_search(Request $request)
    {
        $data['chk_faculty'] = "";   
        $data['chk_campus']  = session('camp_id');
        $data['chk_workline']  = "";
        $month = date('m')-1;
        $year = date('Y');
        #return $year;

        #return session('role_id') ;

        if(session('role_id')== "2"){
            $camp_id = session('camp_id');
        }
        else{
            $camp_id = "";
        }
        #return $camp_id;
        
        $data['faculty'] = mas_faculty::where('record_status','N')->orderby('faculty_id')->get();
        $data['campus'] = mas_campus::where('record_status','N')->orderby('campus_id')->get();
        $data['workline'] = mas_workline::where('record_status','N')->orderby('workline_id')->get();                          
        #$data['search'] = vw_sly_rate::where('record_status','N');
        #$data['search'] = vw_his_person::where('record_status','N');
        $data['search'] = vw_his_person::with('inc_rate_salary')
                                        ->where('record_status','N')
                                        #->where('slip_month',$month)
                                        #->where('slip_year',$year)
                                        ;                                        

            if (isset($request->faculty)) {
                $data['search'] = $data['search']->where('faculty_id',$request->faculty);
                $data['chk_faculty'] = $request->faculty;
            }
            if (isset($camp_id)) {
                $data['search'] = $data['search']->where('campus_id',$camp_id);
                $data['chk_campus'] = $camp_id;
            }             
            
            if (isset($request->workline)) {
                $data['search'] = $data['search']->where('workline_id',$request->workline);
                $data['chk_workline'] = $request->workline;
            }
            /* 
            if (isset($request->lname_search)) {
                $data['search'] = $data['search']->where('lname_th','LIKE %',$request->lname_search);
            }  
            */                             
        $data['search'] = $data['search']->where('statuslist','9')->get();
        #return $data['search'];
        $data['count_search'] = $data['search']->count();
        
        #return $data;

        return view('salary.sly',$data);     
               
    }
}

resources/views/salary/create.blade.php
@extends('layout.master')
@section('content')

<div class="container">

    <div class="card">
        <div class="card-header h3">
            เพิ่มรายการ : CREATE
        </div>

        <div class="card-body">
        <form action="{{ route('expend.store') }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}       

        <div class="row"> {{-- row form --}}
            <div class="mt-2 col-12">
                                            

                {{-- name TH --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ชื่อเรียก ภาษาไทย (Name thai)</span>
                    </div>
                    <input type="text" class="form-control" name="item_name_th" value="" aria-describedby="basic-addon1">
                </div>            
    
                {{-- name EN --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ชื่อเรียก ภาษาอังกฤษ (Name eng)</span>
                    </div>
                    <input type="text" class="form-control" name="item_name_en" value="" aria-describedby="basic-addon1">
                </div>

                {{-- campus --}}                      
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ศูนย์พื้นที่ (Chart)</span>
                    </div>
                    <div class="ml-2">                                                                               
                        @foreach ($campus as $arrCampus)
                            <div class="form-check form-check-inline ml-2"> 
                                <input class="form-check-input" name="item_campus[]" type="checkbox" id="inlineCheckbox1" value="{{ $arrCampus->campus_id }}">
                                <label class="form-check-label" for="inlineCheckbox1">{{ $arrCampus->campus_name_th }}</label>
                            </div>
                        @endforeach                        
                    </div>
                </div>

                {{-- price --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">จำนวนเงิน (บาท)</span>
                    </div>
                    <input type="text" class="form-control" name="item_price" value="" aria-describedby="basic-addon1">
                </div>

                {{-- rate --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ร้อยละ (%)</span>
                    </div>
                    <input type="text" class="form-control" name="item_rate" value="" aria-describedby="basic-addon1">
                </div>
                
                {{-- status --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">สถานะ (Status)</span>
                    </div>
                    <div class="form-check ml-2">
                        <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="N" checked>
                        <label class="form-check-label" for="exampleRadios1">Online</label>
                    </div> 
                    <div class="form-check ml-2">
                        <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="D" >
                        <label class="form-check-label" for="exampleRadios1">Offline</label>
                    </div>                        
                </div>
            </div> {{-- <div class="mt-2"> --}}
        </div>

        <div class="row">
            <button type="submit" class="btn btn-info m-3">SAVE</button>
            <a href="" class="m-3"><button type="button" class="btn btn-secondary">RESET</button></a> 
        </div> {{-- row buttom --}}

        </form> {{-- row form --}}
        </div>{{-- <div class="card-body"> --}}
    </div>

</div>

@endsection

resources/views/salary/edit.blade.php
@extends('layout.master')
@section('content')

<div class="container">

    <div class="card">
        <div class="card-header h3">
            แก้ไขรายการ : EDIT
        </div>

        <div class="card-body">
        
        @foreach ($expend as $arrExpend)

        <form action="{{ url('main/expend/'.$arrExpend->id) }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('PATCH') }}

            <div class="row"> {{-- row form --}}
                <div class="mt-2 col-12">
                                                
                    {{-- name TH --}}            
                    <div class="input-group mb-1">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">ชื่อเรียก ภาษาไทย (Name thai)</span>
                        </div>
                        <input type="text" class="form-control" name="item_name_th" value="{{ $arrExpend->item_name_th }}" aria-describedby="basic-addon1">
                    </div>            
        
                    {{-- name EN --}}            
                    <div class="input-group mb-1">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">ชื่อเรียก ภาษาอังกฤษ (Name eng)</span>
                        </div>
                        <input type="text" class="form-control" name="item_name_en" value="{{ $arrExpend->item_name_en }}" aria-describedby="basic-addon1">
                    </div>

                    {{-- campus --}}                      
                    <div class="input-group mb-1">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">ศูนย์พื้นที่ (Chart)</span>
                        </div>
                        <div class="ml-2">                                                                        
                            @foreach ($campus as $arrCampus)                            
                                <div class="form-check form-check-inline ml-2">         
                                    @if(strpos($arrExpend->item_campus,$arrCampus->campus_id))
                                        @php
                                            $check = "checked";
                                        @endphp
                                    @else
                                        @php
                                            $check = " ";
                                        @endphp
                                    @endif                                
                                    <input class="form-check-input" {{ $check }} name="item_campus[]" type="checkbox" id="inlineCheckbox1" value="{{ $arrCampus->campus_id }}">
                                    <label class="form-check-label" for="inlineCheckbox1">{{ $arrCampus->campus_name_th }}</label>
                                </div>
                            @endforeach                        
                        </div>
                    </div>

                    {{-- price --}}            
                    <div class="input-group mb-1">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">จำนวนเงิน (บาท)</span>
                        </div>
                        <input type="text" class="form-control" name="item_price" value="{{ $arrExpend->item_price }}" aria-describedby="basic-addon1">
                    </div>

                    {{-- rate --}}            
                    <div class="input-group mb-1">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">ร้อยละ (%)</span>
                        </div>
                        <input type="text" class="form-control" name="item_rate" value="{{ $arrExpend->item_rate }}" aria-describedby="basic-addon1">
                    </div>
                    
                    {{-- status --}}            
                    <div class="input-group mb-1">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">สถานะ (Status)</span>
                        </div>
                        @if ($arrExpend->RECORD_STATUS=="N")
                            @php
                                $check_N = "checked";
                                $check_D = "";
                            @endphp
                        @else
                            @php
                                $check_N = "";
                                $check_D = "checked";
                            @endphp
                        @endif
                        <div class="form-check ml-2">
                            <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="N" {{ $check_N }}>
                            <label class="form-check-label" for="exampleRadios1">Online</label>
                        </div> 
                        <div class="form-check ml-2">
                            <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="D" {{ $check_D }}>
                            <label class="form-check-label" for="exampleRadios1">Offline</label>
                        </div>                        
                    </div>
                </div> {{-- <div class="mt-2"> --}}
            </div>

            <div class="row">
                <button type="submit" class="btn btn-info m-3">SAVE</button>
                <a href="" class="m-3"><button type="button" class="btn btn-secondary">RESET</button></a> 
            </div> {{-- row buttom --}}
        </form>

        @endforeach

        </div>{{-- <div class="card-body"> --}}
    </div>

</div>

@endsection

resources/views/salary/index.blade.php
@extends('layout.master')
@section('content')

@if( session('alert'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('alert')}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

<div class="container">
    <div class="card">
        <div class="card-header h3">
            จัดการข้อมูลรายได้ ของบุคลากร ( Income Management )
        </div>
        <div class="card-body">                

            <div class="row"> {{-- search --}}                
            <form action="{{ route('search') }}" method="post"> {{-- form search --}}
            {{ csrf_field() }}
            
                {{-- row --}}            
                <div class="row">
                    <div class="col-6">
                        {{-- 1 --}}            
                        {{-- faculty --}}            
                        <div class="input-group mb-1">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">หน่วยงาน : </span>
                            </div>
                            <select class="form-control" name="faculty" >
                                <option value="">:: เลือก ::</option>         
                                @foreach ($faculty as $arrFaculty)
                                    <option value="{{ $arrFaculty->faculty_id }}"  >{{ $arrFaculty->faculty_name_th }}</option>
                                @endforeach                                 
                            </select>
                        </div>
                    </div>
                    <div class="col-6">
                        {{-- 2 --}}            
                        {{-- faculty --}}            
                        <div class="input-group mb-1">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">ศูนย์พื้นที่ : </span>
                            </div>
                            <select class="form-control" name="campus" >
                                <option value="">:: เลือก ::</option>         
                                @foreach ($campus as $arrCampus)
                                    <option value="{{ $arrCampus->campus_id }}"  >{{ $arrCampus->campus_name_th }}</option>
                                @endforeach                                 
                            </select>
                        </div>
                    </div>                
                </div>

                {{-- row --}}            
                <div class="row">
                    <div class="col-6">
                        {{-- 1 --}}            
                        {{-- workline --}}            
                        <div class="input-group mb-1">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">สายงาน : </span>
                            </div>
                            <select class="form-control" name="workline" >
                                <option value="">:: เลือก ::</option>         
                                @foreach ($workline as $arrWorkline)
                                    <option value="{{ $arrWorkline->workline_id }}  ">{{ $arrWorkline->workline_name_th }}</option>
                                @endforeach                                 
                            </select>
                        </div>
                    </div>
                    <div class="col-6">
                        {{-- 2 --}}            
                        
                    </div>                
                </div>
    
                {{-- name --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ชื่อ - สกุล : </span>
                    </div>
                    <input type="text" class="form-control" name="name_search" value="" disabled aria-describedby="basic-addon1">
                </div>
    
                <div class="input-group mt-2 mb-2">
                    <div class="input-group-append">
                      <button class="btn btn-info" type="submit">SEARCH</button>
                    </div>
                </div>           
                                  
            </form>{{-- form search --}}
        </div> {{-- search --}}
        
        <div class="row d-flex flex-row-reverse"> {{-- add list --}}
            <a href="{{ route('salary.create') }}">
                <button type="button" class="btn btn-success">ADD LIST</button>
            </a>                
        </div>{{-- add list --}}

            <table class="table table-hover">
                <thead>
                    <tr class="card_bg_topic">
                        <th width="5%">#</th>
                        <th width="10%"></th>
                        <th width="40%">name</th>
                        <th width="13%">campus</th>
                        <th width="13%">status</th>
                        <th width="13%">income</th>
                        <th width="5%">manage</th>
                        <th width="5%">print</th>
                    </tr>
                </thead>
                
                <tbody>

                    @if(isset($search))
                        {{-- $search --}}                        
                        @foreach ($search as $key=>$arrSearch)
                            <tr>
                                <td>{{ $key+1 }}</td> 
                                <td>
                                    <img src="https://hrd.rmutsb.ac.th/upload/his/person/photo/{{ $arrSearch->person_picture }}" width="100%" alt="">
                                </td> 
                                <td>
                                    ชื่อ : {{ $arrSearch->fname_th }} {{ $arrSearch->lname_th }}<br>
                                    ตำแหน่ง : {{ $arrSearch->pos_name_th }}<br>
                                    หน่วยงาน : {{ $arrSearch->faculty_name_th }}<br>
                                    ประเภท : {{ $arrSearch->per_type_name_th }}{{ $arrSearch->per_class_name_th }}<br>
                                </td> 
                                <td>{{ $arrSearch->campus_name_th }}</td> 
                                <td>{{ $arrSearch->statuslist_name }}</td> 
                                <td>xx,xxx</td>                         
                                <td>
                                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                                        <i class="fas fa-cogs"></i>
                                    </button>
                                    <div class="dropdown-menu">
                                        <div class="list-group">
                                            <a href="#" class="list-group-item list-group-item-action">
                                                <div class="custom-control custom-switch">
                                                    <input type="checkbox" class="custom-control-input" id="arrAsset->id" checked="checked">
                                                    <label class="custom-control-label" for="arrAsset->id">ออนไลน์</label>                                                                                           
                                                {{-- 
                                                <form action="{{ route('salary_change_status') }}" method="post">
                                                {{ csrf_field() }}
                                                    @if ($arrAsset->RECORD_STATUS == 'D')
                                                        <input type="hidden" name="id" value="arrAsset->id">
                                                        <input type="hidden" name="RECORD_STATUS" value="N">
                                                        <input type="checkbox" class="custom-control-input" id="arrAsset->id"  onchange="submit()">
                                                    @else
                                                        <input type="hidden" name="id" value="arrAsset->id">
                                                        <input type="hidden" name="RECORD_STATUS" value="D">
                                                        <input type="checkbox" class="custom-control-input" id="arrAsset->id" checked="" onchange="submit()">                                
                                                    @endif
                                                    <label class="custom-control-label" for="arrAsset->id">ออนไลน์</label>                                                                                            
                                                </form>    
                                                --}}
                                                </div>
                                            </a>
                                            <a href="{{ url('fin/salary/edit/') }}" class="btn btn-sm list-group-item list-group-item-action"><i class="fas fa-edit text-warning"></i> แก้ไขข้อมูล</a>
                                            <a href="#" class="btn btn-sm list-group-item list-group-item-action" data-toggle="modal" data-target="#myModalarrAsset->id"><i class="far fa-trash-alt text-danger"></i> ลบ</a>                                
                                        </div>                                                                                                                   
                                    </div>
                                </td>                         
                                <td><a href="" class="btn btn-circle btn-primary btn-sm"><i class="fas fa-print"></i></a></td>
                            </tr>                        
                        @endforeach                                              
                    @else
                        null
                    @endif                    
                </tbody>                                        
            </table>            
        </div>
    </div>

</div>

@endsection