routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/','PersonController@index')->middleware('auth');
route::get('profile','PersonController@show_detail')->name('profile');
Route::get('income/{id?}','IncomeController@show');
Route::get('expend/{id?}','ExpendController@show');
Route::get('summary/{id?}','SummaryController@show');
Route::get('account','AccountController@index');

route::get('pdf/{val?}','ExportController@pdf');
route::get('print','ExportController@createPDF');

Route::get('/phpinfo',function(){
    return phpinfo();
});

Route::prefix('manage')->group(function(){
    #Route::get('/','ManageController@index')->name('manage.index');   
    Route::resource('menu','MenuController');   
    Route::get('menu/edit/{id}','MenuController@edit'); 
    Route::post('/menu_change_status','MenuController@change_status')->name('menu_change_status'); 

    Route::resource('group','RolesController');  
    Route::resource('permis','PermisController');  
    #Route::get('permis/{id?}','PermisController');  
    route::get('changepermis/{id?}','PermisController@changepermis');
});


Route::prefix('main')->group(function(){

    Route::resource('person','PersonController'); 
    Route::resource('jd','CategoryController');
    /*
    Route::resource('income','IncomeController'); 
    Route::get('income/edit/{id}','IncomeController@edit'); 
    Route::post('/income_change_status','IncomeController@change_status')->name('income_change_status');

    Route::resource('expend','ExpendController');
    Route::get('expend/edit/{id}','ExpendController@edit'); 
    Route::post('/expend_change_status','ExpendController@change_status')->name('expend_change_status');
    */
    
});

Route::prefix('fin')->group(function(){
    
    Route::resource('salary','SalaryController'); 
    Route::get('salary/edit/{id}','SalaryController@edit'); 
    Route::post('/salary_change_status','SalaryController@change_status')->name('salary_change_status');
    Route::post('/salary/search','SalaryController@search')->name('search');

    Route::resource('assign_expend','AssignExpendController'); 
    Route::post('assign_person/{id}','AssignExpendController@create_person'); 
    Route::get('assign_person/{id}','AssignExpendController@create_person');  
    Route::get('match_per_expend','AssignExpendController@match_person'); 
    Route::get('match_per_expend_step2/{id}','AssignExpendController@match_person_step2');
    Route::post('match_per_expend_step2','AssignExpendController@create_person_expend');  
    Route::get('salary_rate','SalaryController@salary_rate'); 
    Route::post('/rate/search','SalaryController@rate_search')->name('search_rate');


    
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/permissions.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class permissions extends Model
{
    protected $table = "permissions";
    
}

app/roles.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class roles extends Model
{
    protected $table = "roles";
}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\sys_menu;
use App\roles;
use Auth;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['menu'] = sys_menu::where('menu_in','main')
                        ->where('record_status','N')     
                        ->where('system_delete','none')     
                        ->orderby('menu_order')
                        ->get();
        $data['sub_menu'] = sys_menu::where('menu_in','<>','main')
                        ->where('record_status','N')   
                        ->where('system_delete','none')       
                        ->orderby('menu_order')
                        ->get();
                        
        $data['roles'] = roles::all();

        return view('role.group.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['menu'] = sys_menu::where('menu_in','main')
                        ->where('record_status','N')     
                        ->where('system_delete','none')     
                        ->orderby('menu_order')
                        ->get();
        $data['sub_menu'] = sys_menu::where('menu_in','<>','main')
                        ->where('record_status','N')   
                        ->where('system_delete','none')       
                        ->orderby('menu_order')
                        ->get();        

        return view('role.group.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = roles::max('id');
        $id = $id+1;

        $user = Auth::user()->username;

        $arrMenu = json_encode($request->item_menu);

        $roles = new roles;
        $roles->id          =   $id;
        $roles->code        =   $request->code;
        $roles->name        =   $request->name;
        $roles->can_access  =   $arrMenu;
        $roles->level       =   $request->level;
        $roles->record_status = $request->RECORD_STATUS;
        $roles->created_by   =  Auth::user()->username;
        
        $roles->save();
        #return $roles;
        return redirect()->action('RolesController@index')->with('alert','บันทึกข้อมูลเรียบร้อยแล้ว'); 

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/role/permissions/create.blade.php
@extends('layout.master')
@section('content')

<div class="container">

    <div class="card">
        <div class="card-header h3">
            เพิ่มรายการ : CREATE
        </div>

        <div class="card-body">
        <form action=" " method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}  

        <h3>ค้นหา</h3>
        <div class="row"> {{-- row form --}}        
            <div class="col-md-6 col-sm-12">                                                        
                {{-- หน่วยงาน --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">คณะ/สำนัก/สถาบัน</span>
                    </div>
                    <select name="faculty" class="form-control">
                        <option value=""></option>                    
                        @foreach ($faculty as $arrFaculty)
                            <option value="{{ $arrFaculty->faculty_id }}">{{ $arrFaculty->faculty_name_th }}</option>                                                
                        @endforeach
                    </select>
                </div>            
            </div> {{-- <div class="mt-2"> --}} 

            <div class="col-md-6 col-sm-12">                                                        
                {{-- division --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">สาขา/งาน</span>
                    </div>
                    <select name="faculty" class="form-control">
                        <option value=""></option>                    
                        @foreach ($faculty as $arrFaculty)
                            <option value="{{ $arrFaculty->faculty_id }}">{{ $arrFaculty->faculty_name_th }}</option>                                                
                        @endforeach
                    </select>
                </div>            
            </div> {{-- <div class="mt-2"> --}}   

            <div class="col-md-6 col-sm-12">                                                        
                {{-- ชื่อ - สกุล --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ชื่อ - สกุล</span>
                    </div>
                    <input type="text" class="form-control" name="code" value="" aria-describedby="basic-addon1">
                </div>                
            </div> {{-- <div class="mt-2"> --}}

        </div>

        <div class="row">
            <button type="submit" class="btn btn-info m-3">ค้นหา</button>            
        </div> {{-- row buttom --}}

        </form> {{-- row form --}}
        </div>{{-- <div class="card-body"> --}}
    </div>

    <div class="card mt-2 mb-2">
        <div class="card-body">
            <table class="table table-hover table-responsive">
                <thead>
                    <tr class="card_bg_topic">
                        <th>#</th>                            
                        <th width="25%">ชื่อ - นามสกุล</th>
                        <th width="25%">หน่วยงาน</th>
                        <th width="50%">กลุ่มผู้ใช้งาน</th>                                                                                                                                       
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>#</td>
                        <td>#</td>
                        <td>#</td>
                        <td>#</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>

@endsection

resources/views/role/permissions/index.blade.php
@extends('layout.master')
@section('content')

<div class="container">

    <div class="card">
        <div class="card-header h3">กำหนดสิทธิ์ ให้ผู้ใช้งาน</div>

        <div class="card-body">
               
            <button class=" btn btn-success" data-toggle="modal" data-target="#exampleModal"> ADD LIST</button>   
            
            {{-- modal permiss --}}
            <form action="{{ route('permis.store') }}" method="POST" >
            {{ csrf_field() }}  
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">กำหนดสิทธิ์ ผู้ใช้งาน</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                            <section>
                                <b>:: เลือกชื่อ ::</b>
                                <select name="person_id" id="" class="form-control">
                                    @foreach ($User as $user_lise)
                                        <option value="{{ $user_lise->id_card }}">{{ $user_lise->name }}</option>
                                    @endforeach
                                </select>
                            </section>
    
                            <section class="mt-2">
                                <b>:: กำหนดสิทธิ์ ::</b>
                                <select name="role_id" id="" class="form-control">
                                    @foreach ($roles as $roles_list)
                                        <option value="{{ $roles_list->id }}">{{ $roles_list->name }}</option>
                                    @endforeach
                                </select>
                            </section>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                      </div>
                    </div>
                </div>                
            </form>
            {{-- modal permiss --}}
        
        
            <div class="row"> {{-- row form --}}
                <div class="mt-2 col-12">
                    
                    <table class="table table-hover table-responsive">
                        <thead>
                            <tr>
                                <th>#</th>                            
                                <th width="25%">ผู้ใช้งาน</th>
                                <th width="25%">ชื่อ - นามสกุล</th>
                                <th width="50%">กลุ่มผู้ใช้งาน</th>                                
                                <th>แก้ไข</th>                                                                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($permis as $arrPermis)                                                                                              
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $arrPermis->username }}</td>
                                    <td>{{ $arrPermis->name }} </td>
                                    <td>                                        
                                        @foreach ($arrPermis->permissions as $item)
                                            <span class="badge badge-primary">{{ $item->name }}</span>
                                        @endforeach                                         
                                    </td>                                    
                                    <td>
                                        <h3>                                            
                                            <a href="{{ url('manage/permis/') }}" class="btn btn-circle btn-warning btn-sm"><i class="fas fa-edit"></i></a>
                                        </h3>    
                                    </td>                                    
                                </tr>                                                      
                            @endforeach
                        </tbody>
                    </table>

                </div> {{-- <div class="mt-2"> --}}
            </div>                                         
        
            
        </div>{{-- <div class="card-body"> --}}
    </div>

</div>

@endsection