routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});
*/

Route::get('/','PersonController@index')->middleware('auth');
route::get('profile','PersonController@show_detail')->name('profile');
Route::get('income/{id?}','IncomeController@show');
Route::get('expend/{id?}','ExpendController@show');
Route::get('summary/{id?}','SummaryController@show');
Route::get('account','AccountController@index');

route::get('pdf/{val?}','ExportController@pdf');
route::get('print','ExportController@createPDF');

Route::get('/phpinfo',function(){
    return phpinfo();
});

Route::prefix('manage')->group(function(){
    #Route::get('/','ManageController@index')->name('manage.index');   
    Route::resource('menu','MenuController');   
    Route::get('menu/edit/{id}','MenuController@edit'); 
    Route::post('/menu_change_status','MenuController@change_status')->name('menu_change_status'); 

    Route::resource('group','RolesController');  
    Route::resource('permis','PermisController');  
    #Route::get('permis/{id?}','PermisController');  
    route::get('changepermis/{id?}','PermisController@changepermis');
});


Route::prefix('main')->group(function(){

    Route::resource('person','PersonController'); 
    Route::resource('jd','CategoryController');
    /*
    Route::resource('income','IncomeController'); 
    Route::get('income/edit/{id}','IncomeController@edit'); 
    Route::post('/income_change_status','IncomeController@change_status')->name('income_change_status');

    Route::resource('expend','ExpendController');
    Route::get('expend/edit/{id}','ExpendController@edit'); 
    Route::post('/expend_change_status','ExpendController@change_status')->name('expend_change_status');
    */
    
});

Route::prefix('fin')->group(function(){
    
    Route::resource('salary','SalaryController'); 
    Route::get('salary/edit/{id}','SalaryController@edit'); 
    Route::post('/salary_change_status','SalaryController@change_status')->name('salary_change_status');
    Route::post('/salary/search','SalaryController@search')->name('search');

    Route::resource('assign_expend','AssignExpendController'); 
    Route::post('assign_person/{id}','AssignExpendController@create_person'); 
    Route::get('assign_person/{id}','AssignExpendController@create_person');  
    Route::get('match_per_expend','AssignExpendController@match_person'); 
    Route::get('match_per_expend_step2/{id}','AssignExpendController@match_person_step2');
    Route::post('match_per_expend_step2','AssignExpendController@create_person_expend');  
    Route::get('salary_rate','SalaryController@salary_rate'); 
    Route::post('/rate/search','SalaryController@rate_search')->name('search_rate');


    
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;
use App\sys_menu;
use Auth;

use Illuminate\Http\Request;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {         
                        
        $data['MenuContent'] = sys_menu::where('menu_in','main')    
                        ->where('system_delete','none')    
                        ->orderby('menu_order')
                        ->get();
        $data['SubMenuContent'] = sys_menu::where('menu_in','<>','main')    
                        ->where('system_delete','none')                        
                        ->orderby('menu_order')
                        ->get();                        
/*
        $data['topic_name'] = tb_topic_poll::where('topic_group',$system)
                                ->where('topic_id_sub','<>','root')
                                ->where('topic_status','on')
                                ->get();
*/
        #return view('demo_layout.index');
        #return view('layout.master');
        //dd($data);
        return view('menu.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['MenuContent'] = sys_menu::where('menu_in','main')    
                                ->where('system_delete','none')    
                                ->orderby('menu_order')
                                ->get();
        return view('menu.create',$data);        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = sys_menu::max('id');
        $id = $id+1;

        $menu = new sys_menu;
        $menu->id           = $id;
        $menu->menu_order   = $request->menu_order;
        $menu->menu_in      = $request->menu_in;
        $menu->menu_name_th = $request->menu_name_th;
        $menu->menu_target  = $request->menu_target;
        $menu->menu_path    = $request->menu_path;
        $menu->record_status = $request->RECORD_STATUS;
        $menu->menu_code    = $request->menu_code;
        $menu->system_delete = 'none';
        $menu->created_user = Auth::user()->username;
        $menu->save();
        
        #return $menu;
        return redirect('manage/menu')->with('alert','บันทึกข้อมูลเรียบร้อยแล้ว');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data['Menu'] = sys_menu::find($id);
        $data['MenuContent'] = sys_menu::where('menu_in','main')    
                                ->where('system_delete','none')    
                                ->orderby('menu_order')
                                ->get();

        return view('menu.edit',$data);        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $menu = sys_menu::find($id);        
        $menu->menu_order   = $request->menu_order;
        $menu->menu_in      = $request->menu_in;
        $menu->menu_name_th = $request->menu_name_th;
        $menu->menu_target  = $request->menu_target;
        $menu->menu_path    = $request->menu_path;
        $menu->record_status = $request->RECORD_STATUS;
        $menu->menu_code    = $request->menu_code;
        $menu->system_delete = 'none';
        $menu->updated_user = Auth::user()->username;
        $menu->save();
        
        #return $menu;
        return redirect('manage/menu')->with('alert','บันทึกข้อมูลเรียบร้อยแล้ว');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $update = sys_menu::find($id);
        $update->system_delete = "delete";        
        $update->save();  
        return back()->with('alert-class','success')->with('alert','ลบข้อมูลแล้ว');
        #return "ddddd";
    }

    public function change_status(Request $request)
    {
        // return "change_status : ".$id;
        $update = sys_menu::find($request->id);        
        $update->record_status = $request->RECORD_STATUS;
        #$update->updated_by = Auth::user()->username;
        $update->save();
        if($request->record_status == 'N'){
            return back()->with('alert-class','success')->with('alert','ออนไลน์เนื้อหาแล้ว');
        }else{
            return back()->with('alert-class','danger')->with('alert','ออฟไลน์เนื้อหาแล้ว');
        }
    }
}

resources/views/menu/create.blade.php
@extends('layout.master')
@section('content')

<div class="container">

    <div class="card">
        <div class="card-header h3">
            เพิ่มรายการ : CREATE
        </div>

        <div class="card-body">
        <form action="{{ route('menu.store') }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}       

        <div class="row"> {{-- row form --}}
            <div class="mt-2 col-12">
                            
                {{-- name TH --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ชื่อเรียก ภาษาไทย (Name thai)</span>
                    </div>
                    <input type="text" class="form-control" name="menu_name_th" value="" placeholder="ชื่อเรียก"  aria-describedby="basic-addon1">
                </div>                 
                
                {{-- menu_in --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">เป็นเมนูย่อยของ (Sub Menu)</span>
                    </div>
                    <select name="menu_in" id="" class="form-control">
                        <option value="main">::เป็นเมนูหลัก::</option>
                        @foreach ($MenuContent as $item)
                            <option value="{{ $item->id }}">{{ $item->menu_name_th }}</option>
                        @endforeach                        
                    </select>
                </div> 

                {{-- code --}}            
                <div class="input-group mb-1">                    
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">รหัสเรียก (Code)</span>                        
                    </div>                    
                    <input type="text" class="form-control" name="menu_code" value="" >                    
                    <span class="ml-2" style="color: red;">* โปรดระบุ code กรณีที่เป็นเมนูหลัก </span>
                </div>

                {{-- order --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ลำดับแาดงผล (Order)</span>
                    </div>                    
                    <input type="text" class="form-control" name="menu_order" value="" >                    
                </div>

                {{-- menu target --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Target (Menu target)</span>
                    </div>
                    <select name="menu_target" id="" class="form-control">
                        <option value="_self">อยู่หน้าต่างเดิม</option>
                        <option value="_blank">เปิดหน้าต่างใหม่</option>
                    </select>
                </div>

                {{-- path --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">URL (Path)</span>
                    </div>                    
                    <input type="text" class="form-control" name="menu_path" value="" >                    
                </div>
                
                {{-- status --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">สถานะ (Status)</span>
                    </div>
                    <div class="form-check ml-2">
                        <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="N" checked>
                        <label class="form-check-label" for="exampleRadios1">Online</label>
                    </div> 
                    <div class="form-check ml-2">
                        <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="D" >
                        <label class="form-check-label" for="exampleRadios1">Offline</label>
                    </div>                        
                </div>
            </div> {{-- <div class="mt-2"> --}}
        </div>

        <div class="row">
            <button type="submit" class="btn btn-info m-3">SAVE</button>
            <a href="" class="m-3"><button type="button" class="btn btn-secondary">RESET</button></a> 
        </div> {{-- row buttom --}}

        </form> {{-- row form --}}
        </div>{{-- <div class="card-body"> --}}
    </div>

</div>

@endsection

resources/views/menu/edit.blade.php
@extends('layout.master')
@section('content')

<div class="container">

    <div class="card">
        <div class="card-header h3">
            แก้ไขรายการ : EDIT
        </div>

        <div class="card-body">
        
        

        <form action="{{ url('manage/menu/'.$Menu->id) }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('PATCH') }}

        <div class="row"> {{-- row form --}}
            <div class="mt-2 col-12">
                            
                {{-- name TH --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ชื่อเรียก ภาษาไทย (Name thai)</span>
                    </div>
                    <input type="text" class="form-control" name="menu_name_th" value="{{ $Menu->menu_name_th }}">
                </div>                 
                
                {{-- menu_in --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">เป็นเมนูย่อยของ (Sub Menu)</span>
                    </div>
                    <select name="menu_in" id="" class="form-control">                        
                        @php
                            $selected = "";
                            if( $Menu->menu_in == "main"){
                                    $selected = "selected";
                            }
                        @endphp
                            <option value="main" {{ $selected }}>::เป็นเมนูหลัก::</option>                        
                            @foreach ($MenuContent as $item)
                                <option value="{{ $item->id }}" @if($item->id==$Menu->menu_in) selected @endif>
                                    {{ $item->menu_name_th }}
                                </option>
                            @endforeach                                                
                    </select>
                </div> 

                {{-- code --}}            
                <div class="input-group mb-1">                    
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">รหัสเรียก (Code)</span>                        
                    </div>                    
                    <input type="text" class="form-control" name="menu_code" value="{{ $Menu->menu_code }}" >                    
                    <span class="ml-2" style="color: red;">* โปรดระบุ code กรณีที่เป็นเมนูหลัก </span>
                </div>

                {{-- order --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">ลำดับแาดงผล (Order)</span>
                    </div>                    
                    <input type="text" class="form-control" name="menu_order" value="{{ $Menu->menu_order }}" >                    
                </div>

                {{-- menu target --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Target (Menu target)</span>
                    </div>
                    <select name="menu_target" id="" class="form-control">
                        @if ($Menu->menu_target=="_self")
                            @php
                                $select_s = "selected";
                                $select_b = "";
                            @endphp
                        @else
                            @php
                                $select_s = "";
                                $select_b = "checked";
                        @endphp
                    @endif
                        <option value="_self" {{ $select_s }}>อยู่หน้าต่างเดิม</option>
                        <option value="_blank" {{ $select_b }}>เปิดหน้าต่างใหม่</option>
                    </select>
                </div>

                {{-- path --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">URL (Path)</span>
                    </div>                    
                    <input type="text" class="form-control" name="menu_path" value="{{ $Menu->menu_path }}" >                    
                </div>
                
                {{-- status --}}            
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">สถานะ (Status)</span>
                    </div>
                    @if ($Menu->record_status=="N")
                            @php
                                $check_N = "checked";
                                $check_D = "";
                            @endphp
                        @else
                            @php
                                $check_N = "";
                                $check_D = "checked";
                        @endphp
                    @endif
                    <div class="form-check ml-2">
                        <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="N" {{ $check_N }}>
                        <label class="form-check-label" for="exampleRadios1">Online</label>
                    </div> 
                    <div class="form-check ml-2">
                        <input class="form-check-input" type="radio" name="RECORD_STATUS" id="exampleRadios1" value="D" {{ $check_D }} >
                        <label class="form-check-label" for="exampleRadios1">Offline</label>
                    </div>                        
                </div>
            </div> {{-- <div class="mt-2"> --}}
        </div>

            <div class="row">
                <button type="submit" class="btn btn-info m-3">SAVE</button>
                <a href="" class="m-3"><button type="button" class="btn btn-secondary">RESET</button></a> 
            </div> {{-- row buttom --}}
        </form>

        

        </div>{{-- <div class="card-body"> --}}
    </div>

</div>

@endsection

resources/views/menu/index.blade.php
@extends('layout.master')
@section('content')

@if( session('alert'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('alert')}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

<div class="container">

    <div class="card">
        <div class="card-header h3">
            จัดการเมนูระบบ ( Menu Management )
        </div>
        <div class="card-body">
        <a href="{{ route('menu.create') }}">
            <button type="button" class="btn btn-success mb-2" >ADD LIST</button>
        </a>                     
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>name</th>
                        <th>menu in</th>
                        <th>menu traget</th>
                        <th>status</th>
                        <th>edit</th>
                        <th>delete</th>
                    </tr>
                </thead>
                
                <tbody>
                @foreach ($MenuContent as $arrMenuContent)
                @if ($arrMenuContent->record_status == "D")
                    <tr class="table-danger">  
                @else
                    <tr class="table-secondary">  
                @endif                                  
                        <td>{{ $loop->iteration }}</td>
                        <td>
                            <b>{{ $arrMenuContent->menu_name_th }}</b> [ code : {{ $arrMenuContent->menu_code }} ]                                                         
                        </td>
                        <td>{{ $arrMenuContent->menu_in }}</td>
                        <td>{{ $arrMenuContent->menu_target }}</td>
                        <td>
                            <div class="custom-control custom-switch">                            
                                <form action="{{ route('menu_change_status') }}" method="post">
                                {{ csrf_field() }}
                                    @if ($arrMenuContent->record_status == 'D')
                                        <input type="hidden" name="id" value="{{$arrMenuContent->id}}">
                                        <input type="hidden" name="RECORD_STATUS" value="N">
                                        <input type="checkbox" class="custom-control-input" id="{{$arrMenuContent->id}}"  onchange="submit()">
                                    @else
                                        <input type="hidden" name="id" value="{{$arrMenuContent->id}}">
                                        <input type="hidden" name="RECORD_STATUS" value="D">
                                        <input type="checkbox" class="custom-control-input" id="{{$arrMenuContent->id}}" checked="" onchange="submit()">                                
                                    @endif
                                        <label class="custom-control-label" for="{{$arrMenuContent->id}}">ออนไลน์</label>
                                    
                                </form>
                            </div>
                        </td>
                        <td><a href="{{ url('manage/menu/edit/'.$arrMenuContent->id) }}" class="btn btn-circle btn-warning btn-sm"><i class="fas fa-edit"></i></a></td>
                        <td>
                            <a href="" class="btn btn-circle btn-danger btn-sm" data-toggle="modal" data-target="#myModal{{$arrMenuContent->id}}"><i class="far fa-trash-alt"></i></a>
                            <!-- Modal -->
                            <div class="modal fade" id="myModal{{$arrMenuContent->id}}" role="dialog">
                                <div class="modal-dialog">                                
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">          
                                    <h4 class="modal-title text-danger"><b>ยืนยันการลบข้อมูล</b></h4>
                                    </div>
                                    <div class="modal-body">                      
                                        <p>ยืนยันการลบข้อมูล <b>{{ $arrMenuContent->menu_name_th }}</b> โดย <b> -user- </b> ซึ่งเมื่อลบแล้วข้อมูลจะไม่ปรากฎในระบบอีก กรุณาตรวจสอบความถูกต้องก่อนการลบ</p>
                                        <p><i>กรณีต้องการกู้คือกรุณาติดต่อผู้ดูแลระบบ</i></p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <form action="{{ url('manage/menu/'.$arrMenuContent->id) }}" method="post">
                                        {{ csrf_field() }}      
                                        {{ method_field('DELETE') }}                                  
                                            <input type="hidden" name="id" value="{{$arrMenuContent->id}}">
                                            <button type="button" class="btn btn-danger"  onclick="submit()">COMFIRM DELETE</button>
                                        </form>
                                    </div>
                                </div>                                
                                </div>
                            </div>
                        </td>
                    </tr>
                    @foreach ($SubMenuContent as $arrSubMenuContent)
                    @if ($arrSubMenuContent->menu_in == $arrMenuContent->id)
                        @if ($arrSubMenuContent->record_status == "D")
                            <tr class="table-danger">  
                        @else
                            <tr >  
                        @endif                                           
                                <td>-</td>
                                <td>{{ $arrSubMenuContent->menu_name_th }}</td>
                                <td>{{ $arrMenuContent->menu_code }}</td>
                                <td>{{ $arrSubMenuContent->menu_target }}</td>                                
                                <td>
                                    <div class="custom-control custom-switch">                            
                                        <form action="{{ route('menu_change_status') }}" method="post">
                                        {{ csrf_field() }}
                                            @if ($arrSubMenuContent->record_status == 'D')
                                                <input type="hidden" name="id" value="{{$arrSubMenuContent->id}}">
                                                <input type="hidden" name="RECORD_STATUS" value="N">
                                                <input type="checkbox" class="custom-control-input" id="{{$arrSubMenuContent->id}}"  onchange="submit()">
                                            @else
                                                <input type="hidden" name="id" value="{{$arrSubMenuContent->id}}">
                                                <input type="hidden" name="RECORD_STATUS" value="D">
                                                <input type="checkbox" class="custom-control-input" id="{{$arrSubMenuContent->id}}" checked="" onchange="submit()">                                
                                            @endif
                                                <label class="custom-control-label" for="{{$arrSubMenuContent->id}}">ออนไลน์</label>
                                            
                                        </form>
                                    </div>
                                </td>
                                <td><a href="{{ url('manage/menu/edit/'.$arrSubMenuContent->id) }}" class="btn btn-circle btn-warning btn-sm"><i class="fas fa-edit"></i></a></td>
                                <td>
                                    <a href="" class="btn btn-circle btn-danger btn-sm" data-toggle="modal" data-target="#myModal{{$arrSubMenuContent->id}}"><i class="far fa-trash-alt"></i></a>
                                    <!-- Modal -->
                                    <div class="modal fade" id="myModal{{$arrSubMenuContent->id}}" role="dialog">
                                        <div class="modal-dialog">                                
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">          
                                            <h4 class="modal-title text-danger"><b>ยืนยันการลบข้อมูล</b></h4>
                                            </div>
                                            <div class="modal-body">                      
                                                <p>ยืนยันการลบข้อมูล <b>{{ $arrSubMenuContent->menu_name_th }}</b> โดย <b> -user- </b> ซึ่งเมื่อลบแล้วข้อมูลจะไม่ปรากฎในระบบอีก กรุณาตรวจสอบความถูกต้องก่อนการลบ</p>
                                                <p><i>กรณีต้องการกู้คือกรุณาติดต่อผู้ดูแลระบบ</i></p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <form action="{{ url('manage/menu/'.$arrSubMenuContent->id) }}" method="post">
                                                {{ csrf_field() }}      
                                                {{ method_field('DELETE') }}                                  
                                                    <input type="hidden" name="id" value="{{$arrSubMenuContent->id}}">
                                                    <button type="button" class="btn btn-danger"  onclick="submit()">COMFIRM DELETE</button>
                                                </form>
                                            </div>
                                        </div>                                
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endif                      
                    @endforeach
                @endforeach
                </tbody>                                
            </table>

        </div>
    </div>

</div>

@endsection